name: Terracotta Bank - Publish Release Package

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly at midnight on Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "corretto"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

      - name: Install Packages
        run: sudo apt-get install -y libxml2-utils gnupg2

      - name: Import GPG Keys From Ubuntu Keyserver
        run: gpg --keyserver keyserver.ubuntu.com --recv-keys 7E8F1053

      - name: Build WAR with Gradle
        run: ./gradlew clean build -x test

      - name: Fetch Latest Contrast Agent Version
        id: fetch-latest-contrast-agent-version
        run: |
          # Fetch the Maven metadata XML
          curl -s https://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/maven-metadata.xml -o maven-metadata.xml

          # Extract the latest release version
          LATEST_AGENT_RELEASE_VERSION=$(xmllint --xpath 'string(/metadata/versioning/release)' maven-metadata.xml)

          echo "Latest release version is $LATEST_AGENT_RELEASE_VERSION"
          echo "latest_agent_release_version=$LATEST_AGENT_RELEASE_VERSION" >> $GITHUB_OUTPUT

      # - name: Get Latest Release Flag
      #   id: get-latest-release-flag
      #   run: |
      #     echo "Returning Static Value for Now"
      #     # TODO: Need to add GitHub API call to get latest release tag

      #     LATEST_TAG=v6.1.1
      #     echo "Latest release tag is $LATEST_TAG"
      #     echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      # - name: Extract Previous Agent Version From Tag
      #   id: extract-previous-agent-version-from-tag
      #   run: |
      #     LATEST_TAG=${{ steps.get-latest-release-flag.outputs.latest_tag }}
      #     PREVIOUS_AGENT_RELEASE_VERSION=${LATEST_TAG#v}
      #     echo "Previous agent version is $PREVIOUS_AGENT_RELEASE_VERSION"
      #     echo "previous_agent_release_version=$PREVIOUS_AGENT_RELEASE_VERSION" >> $GITHUB_OUTPUT

      # - name: Download Latest Release Contrast Agent If Newer
      #   run: |
      #     PREVIOUS_AGENT_RELEASE_VERSION=${{ steps.extract-previous-agent-version-from-tag.outputs.previous_agent_release_version }}
      #     LATEST_AGENT_RELEASE_VERSION=${{ steps.fetch-latest-contrast-agent-version.outputs.latest_agent_release_version }}

      #     if [ "$LATEST_AGENT_RELEASE_VERSION" != "$PREVIOUS_AGENT_RELEASE_VERSION" ]; then
      #       echo "Downloading Contrast Agent version $LATEST_AGENT_RELEASE_VERSION"
      #       wget -O contrast-agent.jar "https://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/${LATEST_AGENT_RELEASE_VERSION}/contrast-agent-${LATEST_AGENT_RELEASE_VERSION}.jar"
      #       # wget -O contrast-agent.jar.sha1 "https://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/${LATEST_AGENT_RELEASE_VERSION}/contrast-agent-${LATEST_AGENT_RELEASE_VERSION}.jar.sha1"
      #       # gpg --verify contrast-agent.jar
      #     else
      #       echo "Already using the latest version: $PREVIOUS_AGENT_RELEASE_VERSION"
      #       exit 1
      #     fi

      - name: Download Latest Release Contrast Agent
        run: |
          LATEST_AGENT_RELEASE_VERSION=${{ steps.fetch-latest-contrast-agent-version.outputs.latest_agent_release_version }}
          echo "Downloading Contrast Agent version $LATEST_AGENT_RELEASE_VERSION"
          wget -O contrast-agent.jar "https://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/${LATEST_AGENT_RELEASE_VERSION}/contrast-agent-${LATEST_AGENT_RELEASE_VERSION}.jar"


      - name: Prepare Terracotta Bank Release Package
        id: prepare-terracotta-bank-release-package
        run: |
          TERRACOTTA_BANK_VERSION=0.0.1-SNAPSHOT
          LATEST_AGENT_RELEASE_VERSION=${{ steps.fetch-latest-contrast-agent-version.outputs.latest_agent_release_version }}
          mkdir terracotta-bank
          cp build/libs/terracotta-bank-servlet-${TERRACOTTA_BANK_VERSION}.war terracotta-bank/terracotta.war
          cp contrast-agent.jar terracotta-bank/
          cp scripts/* terracotta-bank/
          zip -r terracotta-release.zip terracotta-bank/

      - name: Create Terracotta Bank Release
        id: create-terracotta-bank-release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.fetch-latest-contrast-agent-version.outputs.latest_agent_release_version }}
          tag_name: v${{ steps.fetch-latest-contrast-agent-version.outputs.latest_agent_release_version }}
          draft: true
          prerelease: true
          files: |
            terracotta-release.zip
